In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

data=pd.read_csv("spam.csv",encoding="latin-1")

data.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [2]:
print(data.shape)
print(data.columns)
data.info()

(5572, 5)
Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   str
 1   v2          5572 non-null   str
 2   Unnamed: 2  50 non-null     str
 3   Unnamed: 3  12 non-null     str
 4   Unnamed: 4  6 non-null      str
dtypes: str(5)
memory usage: 217.8 KB

In [3]:
print(data['v1'].value_counts())

v1
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
data=data.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'])
data=data.rename(columns={'v1':'label','v2':'message'})
data.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
print(data.isnull().sum())
print("Duplicate rows:",data.duplicated().sum())

label      0
message    0
dtype: int64
Duplicate rows: 403

In [7]:
data['label']=data['label'].map({'ham':0,'spam':1})
data.head()

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [8]:
X=data['message']
Y=data['label']

print(X.head())
print(Y.head())

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: message, dtype: str
0    0
1    0
2    1
3    0
4    0
Name: label, dtype: int64

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(stop_words='english')
X=tfidf.fit_transform(X)
print(X.shape)

(5572, 8404)

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

print(X_train.shape)
print(Y_test.shape)

(4457, 8404)
(1115,)

In [11]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train,Y_train)

print("Model trained successfully!")

Model trained successfully!

In [12]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
y_pred=model.predict(X_test)
print("Accuracy:",accuracy_score(Y_test,y_pred))
print(confusion_matrix(Y_test,y_pred))
print(classification_report(Y_test,y_pred))

Accuracy: 0.968609865470852
[[965   0]
 [ 35 115]]
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       965
           1       1.00      0.77      0.87       150

    accuracy                           0.97      1115
   macro avg       0.98      0.88      0.93      1115
weighted avg       0.97      0.97      0.97      1115

In [13]:
message = ["Congratulations! You have won a FREE iPhone. Click here to claim your prize."]

message_tfidf = tfidf.transform(message)

prediction = model.predict(message_tfidf)

if prediction[0] == 1:
    print("Spam Message")
else:
    print("Ham (Not Spam)")

Spam Message

In [14]:
import pickle
pickle.dump(model, open("spam_model.pkl", "wb"))

print("Model saved successfully!")

Model saved successfully!